---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
    exclude_fingerprints:
      - cf57ca3c27caad6b61115dd37bc1fc02
      - 53af6b1590a0711e6b6d8204fef9c82f
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/
- db/
- spec/
- vendor/
- "app/assets/stylesheets/font-awesome.css"
- "app/assets/javascripts/*.min.js"
- "app/assets/stylesheets/*.min.css"
- "app/assets/stylesheets/bootstrap-social.css"
