# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03772d5763da09a7be8197f38d61a435053ee2ad3c90485b86a603a443284f6cc6018e944fb0184150e0d855e215ca44215992191db399c4ccf66e3e359aeeb6

test:
  secret_key_base: ac544ceba057c62fbbe36e5735d8ddb29ccbb16f920e9a63a470d4f23ceca0be25b2a7e10e134499f9d6bb47759d76546949c4b99c39aba8cb38c34e7410774e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
